### PR TITLE
[stm] retry Abort when transaction is inconsistent

### LINKED ISSUE #1158: [BUG]: STM reading inconsistent values
### Version

0.18.0

### Scala Version

3.6.4

### Expected Behavior

Since the 2 `TRef`s initially contain equal values, and I only ever write into them equal values, I expect never to observe non-equal values in a single transaction. That is, I expect the program to exit without an exception.

### Actual Behavior

The program exits with an exception like this:
```
Exception in thread "main" java.lang.AssertionError: a111111111111111111111111 != a1111111111111111111111111
```

### Steps to Reproduce

```scala
object StmTest extends KyoApp {
  run {
    for {
      // initially they contain equal values:
      r1 <-STM.run(TRef.init("a"))
      r2 <-STM.run(TRef.init("a"))
      txn1 = for {
        v1 <- r1.get
        v2 <- r2.get
        // we only write equal values:
        _ <- r1.set(v1 + "1")
        _ <- r2.set(v2 + "1")
      } yield ()
      txn2 = r1.get.map { v1 =>
        r2.get.map { v2 =>
          if (v1 == v2) {
            ()
          } else {
            // observed non-equal values:
            Abort.panic(new AssertionError(s"${v1} != ${v2}")) // <- fails here
          }
        }
      }
      once = Async.zip(STM.run(txn1), STM.run(txn2))
      _ <- Async.foreachDiscard(1 to 100000, concurrency = 8) { _ => once }
    } yield ()
  }
}
```

### Current Workaround

_No response_

### PR DESCRIPTION
**Pull request by fwbrasil**
Fixes #1158

### Problem

When a transaction is rolled back due to an `Abort`, the `STM` effect simply propagates the error. This can be a surprising behavior when the `Abort` happened due to an inconsistent state during the transaction execution, which is an expected scenario given that consistency is checked at commit time. 

### Solution

In case of errors, check if the ref log is still valid and, if not, wrap the error into `FailedTransaction` to trigger a retry in case the schedule permits.

### Notes

- I've added `Abort.recoverError` and `Abort.foldError` since it seems a relatively common pattern.

### CODE REVIEW

File: kyo-stm/shared/src/main/scala/kyo/STM.scala [hunk 1]
```diff
@@ -202,6 +137,81 @@ object STM:
 
     end run
 
+    private def commit[A, S](tid: Long, log: TRefLog, probe: Boolean = false)(using AllowUnsafe): Boolean =
```
Comment (fwbrasil) [inline kyo-stm/shared/src/main/scala/kyo/STM.scala:140]: The overall logic here is still the same. I've refactored it into a new method that returns a `Boolean` indicating if the commit was successful, introduced `boundary`/`break` to replace the exception throwing, and add a `probe` parameter to indicate that the commit should only validate and not write values to refs

File: kyo-stm/shared/src/main/scala/kyo/STM.scala [hunk 2]
```diff
@@ -2,10 +2,7 @@ package kyo
 
 import kyo.Result.Failure
 import scala.annotation.tailrec
-
-/** A FailedTransaction exception that is thrown when a transaction fails to commit. Contains the frame where the failure occurred.
-  */
-class FailedTransaction()(using Frame) extends KyoException
```
Comment (fwbrasil) [inline kyo-stm/shared/src/main/scala/kyo/STM.scala:8]: moved to the end of the file

File: kyo-stm/shared/src/main/scala/kyo/STM.scala [hunk 3]
```diff
@@ -93,100 +90,38 @@ object STM:
...
-                                        end try
-                                    }
-                            end match
+                TID.useNew { tid =>
+                    v.handle(
+                        Abort.recoverError[E] { error =>
+                            // Retry arbitrary E failures in case the transaction is inconsistent
+                            Var.use[TRefLog] { log =>
+                                IO.Unsafe {
+                                    if !commit(tid, log, probe = true) then
```
Comment (fwbrasil) [inline kyo-stm/shared/src/main/scala/kyo/STM.scala:104]: note `probe = true` to just probe the commit without updating refs

File: kyo-stm/shared/src/main/scala/kyo/STM.scala [hunk 4]
```diff
@@ -202,6 +137,81 @@ object STM:
...
+                // Commit multiple refs
+                // Flattened representation of the log
+                val array = new Array[Any](size * 2)
+
+                boundary {
+
+                    var i = 0
+                    // Pre-validate and dump the log to the flat array
+                    logMap.foreachEntry { (ref, entry) =>
+                        // This code uses exception throwing because
```
Comment (hearnadam) [inline kyo-stm/shared/src/main/scala/kyo/STM.scala:166]: minor: could use an update.

**Comment by durban** [comment]
I've tried this branch, and I can confirm that it solves my original problem in #1158. (It doesn't seem to provide full opacity, but as far as I can tell, it doesn't try to, so that's fine.)

One question: out of curiosity, I've tried replacing `Abort.panic(new AssertionError(...))` in my original test in #1158 with `throw new AssertionError(...)`. (I was interested in what would happen with a "random exception" thrown due to observing an inconsistency.) It fails with a seemingly unrelated error:

```
[error] Exception in thread "main" java.lang.NullPointerException: Cannot invoke "String.indexOf(int, int)" because "self" is null
[error]         at kyo.Frame$package$Frame$.findNextSeparator(Frame.scala:44)
[error]         at kyo.Frame$package$Frame$.snippet(Frame.scala:63)
[error]         at kyo.Frame$package$Frame$.snippetShort(Frame.scala:69)
[error]         at kyo.kernel.internal.Trace$Owner.parse$1(Trace.scala:107)
[error]         at kyo.kernel.internal.Trace$Owner.enrich(Trace.scala:111)
[error]         at kyo.kernel.internal.Trace$Owner.kyo$kernel$internal$Trace$Owner$$inline$enrich(Trace.scala:94)
[error]         at kyo.scheduler.IOTask.eval(IOTask.scala:39)
[error]         at kyo.scheduler.IOTask.run(IOTask.scala:84)
[error]         at kyo.scheduler.Worker.runTask(Worker.scala:257)
[error]         at kyo.scheduler.Worker.run(Worker.scala:219)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[error]         at java.base/java.lang.Thread.run(Thread.java:1583)
```

I don't know what this could be, but maybe it's useful information... :man_shrugging: 

(In general, is `Abort.panic` equivalent to throwing an exception? Or is that not a thing?)

**Comment by durban** [comment]
Sure, I've opened #1172.

**Comment by fwbrasil** [comment]
Merging since we have a confirmation that the issue is fixed
