### PR TITLE
[prelude] Abort with literal types

### LINKED ISSUE #739: Abort with literal strings
Users currently need to create new types in case they need to distinguish different failure scenarios. Allowing literal strings seems a good way to make the effect more convenient:

```scala
def test(v: Int): Int < Abort["negative" | "positive"] =
    if v < 0 then Abort.failLiteral("negative")
    else if v > 0 then Abort.failLiteral("positive")
    else 42

val a: Result["negative" | "positive", Int] < Any = 
    Abort.run(test(1))

val b: Result["negative", Int] < Abort["positive"] = 
    Abort.run["negative"](test(1))
```

I think we'd need a separate method like `failLiteral` to avoid inference issues and fail compilation if the string isn't statically known. We could allow other literal types like integers as well but I'm not sure it'd make much sense.

The change in `Abort` seems easy but we'd need to make `SafeClassTag` support literal types, which is a more involved change.

### PR DESCRIPTION
**Pull request by hearnadam**
Fixes #739 

### Problem
With `Abort.fail`, manual type annotations are required to write expressions that fail with literal types.

### Solution
Add an object `literal` to `Abort` to enable failing with literal types, namely Strings.

### Notes
The functions will degrade to non-literal behavior in a generic scope.

### CODE REVIEW

File: kyo-prelude/shared/src/test/scala/kyo/AbortTest.scala [hunk 1]
```diff
@@ -1214,4 +1214,70 @@ class AbortTest extends Test:
         }
     }
 
+    "literal" - {
```
Comment (fwbrasil) [inline kyo-prelude/shared/src/test/scala/kyo/AbortTest.scala:1217]: can you also test inference? 

```scala
val result = ...
val _: ExpectedType = result
```

File: kyo-prelude/shared/src/test/scala/kyo/AbortTest.scala [hunk 2]
```diff
@@ -1214,4 +1214,70 @@ class AbortTest extends Test:
...
+            def when(b: Boolean): Unit < Abort["TOO_BIG"] =
+                Abort.literal.when(b)("TOO_BIG")
+
+            val result: Unit < Abort["TOO_BIG"] = when(false)
+            assert(Abort.run(result).eval == Result.unit)
+            assert(Abort.run(when(true)).eval == Result.fail("TOO_BIG"))
+        }
+
+        "effects" in {
+            val result = Env.run(15) {
```
Comment (fwbrasil) [inline kyo-prelude/shared/src/test/scala/kyo/AbortTest.scala:1257]: what's the type of `result` here?

File: kyo-prelude/shared/src/main/scala/kyo/Abort.scala [hunk 3]
```diff
@@ -487,4 +487,72 @@ object Abort:
...
+      * The literal namespace ensures that error types are preserved as singleton types rather than being widened to their base types. This
+      * is particularly useful when you want to maintain precise type information about specific error values.
+      *
+      * For example:
+      * ```scala
+      * val error1 = Abort.fail("error")         // Nothing < Abort[String]
+      * val error2 = Abort.literal.fail("error") // Nothing < Abort["error"]
+      * ```
+      */
+    object literal:
```
Comment (fwbrasil) [inline kyo-prelude/shared/src/main/scala/kyo/Abort.scala:501]: don't we need `run` methods for literals as well?

File: kyo-prelude/shared/src/test/scala/kyo/AbortTest.scala (hunk 2 above)
Comment (hearnadam) [reply kyo-prelude/shared/src/test/scala/kyo/AbortTest.scala:1257]: Good catch. `Abort.run` wasn't preserving the correct type in a generic context. I added `literal.run`

File: kyo-prelude/shared/src/main/scala/kyo/Abort.scala (hunk 3 above)
Comment (hearnadam) [reply kyo-prelude/shared/src/main/scala/kyo/Abort.scala:501]: Not in all contexts, but it will help preserve the type information in some cases (mixing effects). Added.

**Review by fwbrasil — APPROVED** [review]
