### PR TITLE
Aspect: re-enable tests on Scala Native

### LINKED ISSUE #845: Scala Native crash for Aspect
Scala Native is crashing after https://github.com/getkyo/kyo/pull/839. I had the same issue in https://github.com/getkyo/kyo/pull/843 after adding an aspect to `Parse`.

```
[error] /home/runner/work/kyo/kyo/kyo-prelude/native/target/scala-3.5.2/native-test/generated/1a0c1.ll:585314:52: error: '@_SM11kyo.Aspect$D15init$$anonfun$1L16java.lang.ObjectL15scala.Function1L16java.lang.ObjectEpT11kyo.Aspect$' defined with type 'i8* (i8*, i8*)*' but expected 'i8* (i8*)*'
[error]   %_4000001 = call dereferenceable_or_null(16) i8* @"_SM11kyo.Aspect$D15init$$anonfun$1L16java.lang.ObjectL15scala.Function1L16java.lang.ObjectEpT11kyo.Aspect$"(i8* dereferenceable_or_null(16) %_2)
[error]                                                    ^
[error] 1 error generated.
[info] Compiling to native code (5815 ms)
[info] Total (17149 ms)
[error] Failed to compile /home/runner/work/kyo/kyo/kyo-prelude/native/target/scala-3.5.2/native-test/generated/1a0c1.ll
[error] (kyo-preludeNative / Test / nativeLink) Failed to compile /home/runner/work/kyo/kyo/kyo-prelude/native/target/scala-3.5.2/native-test/generated/1a0c1.ll
```

It seems an issue with the new `Cut` encoded as a generic function:

```scala
type Cut[I[_], O[_], S] = [C] => (I[C], I[C] => O[C] < S) => O[C] < S
```

To reproduce:

```
mv kyo-prelude/jvm/src/test/scala/kyo/AspectTest.scala kyo-prelude/shared/src/test/scala/kyo/AspectTest.scala
mv kyo-prelude/jvm/src/test/scala/kyo/ParseTest.scala kyo-prelude/shared/src/test/scala/kyo/ParseTest.scala
```

### PR DESCRIPTION
**Pull request by hearnadam**
Fixes #845 

### Problem
Aspect was causing a crash on Scala Native that was fixed in 0.5.6.

### Solution
Move tests back to `shared`

### CODE REVIEW

File: kyo-data/shared/src/main/scala/kyo/KyoException.scala [hunk 1]
```diff
@@ -55,12 +55,12 @@ class KyoException private[kyo] (
 
         if Environment.isDevelopment then
             val msg = frame.render(
-                ("⚠️ KyoException".red.bold :: Maybe(message).toList ::: detail.toList)
+                ("⚠️ KyoException".red.bold :: message :: detail.toList)
```
Comment (hearnadam) [inline kyo-data/shared/src/main/scala/kyo/KyoException.scala:58]: Now that `message` has a default of `""` this should be safe.

File: kyo-data/shared/src/main/scala/kyo/KyoException.scala [hunk 2]
```diff
@@ -55,12 +55,12 @@ class KyoException private[kyo] (
...
                     .map(_.show)*
             )
             s"\n$msg\n"
         else
-            detail.map(_.toString).getOrElse(null)
+            (message + detail.fold("")(" " + _)).toString
```
Comment (hearnadam) [inline kyo-data/shared/src/main/scala/kyo/KyoException.scala:63]: `message` was missing - which seems more important than detail 🙂

Comment (fwbrasil) [reply kyo-data/shared/src/main/scala/kyo/KyoException.scala:63]: ouch
