### PR TITLE
fix and enable JS tests

### LINKED ISSUE #1138: Review disabled tests in JS
The disabling of JS tests wasn't very strict in the initial development of the cross compilation. We need to review if they're correct. The main limitation are scenarios where two threads are required, for example when testing interruptions or waiting for some condition triggered by a concurrent computation.

### PR DESCRIPTION
**Pull request by fwbrasil**
Fixes #1138

### Problem

We have tests disabled in JS because they require multiple threads.

### Solution

Fix tests to avoid hot loops hogging the JS thread.

### CODE REVIEW

File: kyo-core/shared/src/main/scala/kyo/Async.scala [hunk 1]
```diff
@@ -157,6 +157,30 @@ object Async:
...
+      * automatic preemption makes this less critical.
+      *
+      * @param f
+      *   The computation to execute after yielding
+      * @return
+      *   The result of the computation wrapped in an Async effect
+      */
+    def yieldWith[A, S](f: => A < S)(using Frame): A < (Async & S) =
+        Async.run(()).map(_.use(_ => f))
+
```
Comment (fwbrasil) [inline kyo-core/shared/src/main/scala/kyo/Async.scala:183]: new methods to yield to the scheduler

File: kyo-core/shared/src/main/scala/kyo/internal/BaseKyoCoreTest.scala [hunk 2]
```diff
@@ -18,4 +18,15 @@ private[kyo] trait BaseKyoCoreTest extends BaseKyoKernelTest[Abort[Any] & Async
             IO.Unsafe.evalOrThrow
         )
     end run
+
+    def untilTrue[S](f: => Boolean < S): Unit < (Async & S) =
```
Comment (fwbrasil) [inline kyo-core/shared/src/main/scala/kyo/internal/BaseKyoCoreTest.scala:22]: moved from the kernel so it's possible to use `Retry` and avoid a hot loop

**Review by hearnadam — APPROVED** [review]
