### PR TITLE
Reimplement parallel map functions without state

### LINKED ISSUE #1192: [BUG]: Missed signals in Stream.mapChunkPar
### Version

0.19.0

### Scala Version

3.7.0

### Expected Behavior

_No response_

### Actual Behavior

`SignalRef` is a primitive that doesn't guarantee delivery of changes. As documented in the scaladoc, It's designed for UI-like use cases where missed signals are ok. `Stream.mapChunkPar`'s tests are failing I believe due to this characteristic. We need to reimplement the method without `SignalRef`.

### Steps to Reproduce

Revert https://github.com/getkyo/kyo/commit/9ed7aa269c102c72e58eb57c126b1f8bc27d30b2 and run `StreamCoreExtensionsTest`. It's flaky so it might need a few runs.

### Current Workaround

_No response_

### PR DESCRIPTION
**Pull request by johnhungerford**
Fixes #1192 

### Problem

`mapChunkPar` tests were flaky due to the use of `SignalRef`

### Solution

Use a channel of size `parallel` instead to limit concurrency.

Also reimplemented `mapPar`, `mapParUnordered`, and `mapChunkParUnordered` similarly without state (they were using `AtomicRef`). I think they are a bit easier to understand this way, and are more consistent with each other now.

### CODE REVIEW

**Comment by johnhungerford** [comment]
@ahoy-jon I added some comments [as promised on discord](https://discord.com/channels/1087005439859904574/1245754417840394313/1381275739869151242).  I also made a further simplification eliminating the need to use a stateful stream handler.

File: kyo-core/shared/src/main/scala/kyo/StreamCoreExtensions.scala [hunk 1]
```diff
@@ -304,80 +304,59 @@ object StreamCoreExtensions:
...
-                                    onPanic = e => Abort.run(channel.put(Absent)).andThen(Abort.panic(e))
-                                )(handledStream)
-
-                            background.map: backgroundFiber =>
-                                emitMaybeChunksFromChannel(channel).andThen:
-                                    backgroundFiber.get.unit
-                }
+                Channel.initWith[Maybe[Chunk[V2]]](bufferSize): channelOut =>
+                    // Staging channel acts as concurrency limiter: contains fibers that either contain a
+                    // chunk to be published, or a signal to continue or end
```
Comment (fwbrasil) [inline kyo-core/shared/src/main/scala/kyo/StreamCoreExtensions.scala:312]: thanks for the comments! it makes the review much easier

File: kyo-core/shared/src/main/scala/kyo/StreamCoreExtensions.scala [hunk 2]
```diff
@@ -304,80 +304,59 @@ object StreamCoreExtensions:
...
+                    Channel.initWith[Fiber[E | Closed, Boolean | Chunk[V2]]](parallel - 1): stagingChannel =>
```
Comment (fwbrasil) [inline kyo-core/shared/src/main/scala/kyo/StreamCoreExtensions.scala:313]: no need to change it but wouldn't a `Meter` work well for this?

**Review by fwbrasil — APPROVED** [review]

File: kyo-core/shared/src/main/scala/kyo/StreamCoreExtensions.scala (hunk 2 above)
Comment (johnhungerford) [reply kyo-core/shared/src/main/scala/kyo/StreamCoreExtensions.scala:313]: The problem with `Meter` is ensuring that the end-of-stream signal is not published until all pending transformations have published.
