### PR TITLE
Typemap deterministic get

### LINKED ISSUE #545: TypeMap retrieval is non-deterministic
This fails:
```scala
        "deterministic" in {
            trait A
            trait B extends A
            val b = new B {}
            trait C extends A
            val c = new C {}
            trait D extends A
            val d = new D {}
            trait E extends A
            val e = new E {}
            trait F extends A
            val f = new F {}
            trait G extends A
            val g = new G {}
            trait H extends A
            val h = new H {}
            trait I extends A
            val i = new I {}
            trait J extends A
            val j = new J {}
            trait K extends A
            val k = new K {}

            var map: TypeMap[A] = TypeMap(b)
            assert(map.get[A] eq b)
            map = map.add(c)
            assert(map.get[A] eq b)
            map = map.add(d)
            assert(map.get[A] eq b)
            map = map.add(e)
            assert(map.get[A] eq b)
            map = map.add(f)
            assert(map.get[A] eq b)
            map = map.add(g)
            assert(map.get[A] eq b)
            map = map.add(h)
            assert(map.get[A] eq b)
            map = map.add(i)
            assert(map.get[A] eq b)
            map = map.add(j)
            assert(map.get[A] eq b)
            map = map.add(k)
            assert(map.get[A] eq b)
        }
```

After adding `b` and `c` it will return `b` but after adding `d` it will now return `d`.

The full order is: `b` `b` `d` `e` `e` `e` `h` `h` `j` `j`

I realised this possibility while tinkering with #494.

### PR DESCRIPTION
**Pull request by steinybot**
Fixes #545

I would probably expect it to retrieve the last modified first but I couldn't think of an easy way to do this efficiently. First modified first still seems better than a seemingly random order.

### CODE REVIEW

File: kyo-core/shared/src/main/scala/kyo/typeMap.scala [hunk 1]
```diff
@@ -12,22 +12,13 @@ object TypeMap:
...
-                        val (tag, item) = it.next()
-                        if tag <:< t then
-                            sub = item.asInstanceOf[B]
-                    end while
-                catch
-                    case _: NoSuchElementException => fatal
-                end try
-                sub
-            end if
+            val it = self.iterator
```
Comment (fwbrasil) [inline kyo-core/shared/src/main/scala/kyo/typeMap.scala:15]: would it be possible to keep the exact lookup first? The linear search on every `get` seems expensive.

Comment (steinybot) [reply kyo-core/shared/src/main/scala/kyo/typeMap.scala]: Woops. Yeah that was an oversight. Fixed.

**Comment by hearnadam** [comment]
Thanks for the PR - can you run the benchmarks before and after?

I think this is likely quite valuable, but may require a custom implementation for performance reasons...

**Comment by fwbrasil** [comment]
Agree on the need for a dedicated data structure but fixing the indeterminism seems already valuable. A prefix tree based on the hierarchy of the tags might be a good option for a more optimized representation. It's possible to recover the type hierarchy from the tag payload.

**Comment by hearnadam** [comment]
The dark horse option is to sort the iterator of the standard map. This would maintain the exact same cost for all operations aside from `get` - when `get` exact fails. My fear is that it could be significant overhead where users are using subtypes as the elements in their map...

**Comment by fwbrasil** [comment]
@hearnadam how do you feel about merging this fix for now? We can follow up with optimization later

File: kyo-core/shared/src/main/scala/kyo/typeMap.scala [hunk 2]
```diff
@@ -12,22 +12,16 @@ object TypeMap:
...
-                    case _: NoSuchElementException => fatal
-                end try
-                sub
-            end if
+            def search: Any =
+                val it = self.iterator
+                while it.hasNext do
+                    val (tag, item) = it.next()
+                    if tag <:< t then
+                        return item
```
Comment (hearnadam) [inline kyo-core/shared/src/main/scala/kyo/typeMap.scala:20]: Generally prefer not using premature returns, but seems okay in this case.

**Review by hearnadam — APPROVED** [review]

File: kyo-core/shared/src/main/scala/kyo/typeMap.scala (hunk 2 above)
Comment (steinybot) [reply kyo-core/shared/src/main/scala/kyo/typeMap.scala:20]: Same here actually but the trailrec loop didn't look as good.
