### PR TITLE
Return Unit for `TypeMap#get[Any]` on empty TypeMap

### LINKED ISSUE #608: TypeMap.empty.get[Any] throws fatal
```
import kyo.*

TypeMap.empty.get[Any]
```
```
Caused by: java.lang.RuntimeException: fatal: kyo.TypeMap of contents [TypeMap()] missing value of type: [scala.Any].
```

Either we need to make `empty` `Map(Tag[Any] -> ())` OR we need to special case.

### PR DESCRIPTION
**Pull request by hearnadam**
Fixes #608

### CODE REVIEW

File: kyo-data/shared/src/main/scala/kyo/TypeMap.scala [hunk 1]
```diff
@@ -21,7 +21,8 @@ object TypeMap:
                 end while
                 fatal
             end search
-            self.getOrElse(t.erased, search).asInstanceOf[B]
+            if isEmpty && t =:= Tag[Any] then ().asInstanceOf[B]
```
Comment (fwbrasil) [inline kyo-data/shared/src/main/scala/kyo/TypeMap.scala:24]: Could we have issues with other super types like `AnyRef`, `AnyVal`, `Matchable`?

Comment (hearnadam) [reply kyo-data/shared/src/main/scala/kyo/TypeMap.scala:24]: No because those don't conform to the type bound `Any`. I can add a test for it if you want.

`TypeMap.empty.get[AnyRef]` fails to compile.

Comment (fwbrasil) [reply kyo-data/shared/src/main/scala/kyo/TypeMap.scala:24]: I see, makes sense. I think tests for that can be useful to avoid issues with future changes.
