### PR TITLE
fix: ScalaJS's KyoApp

### LINKED ISSUE #784: ScalaJS with KyoApp
I tried starting a scalajs project with `KyoApp`, but code as simple as below doesn't work:
```scala
import kyo.*

object ScalaJsApp extends KyoApp {
  run(for {
    _ <- println("1")
    _ <- println("2")
  } yield {})
}
```
running that in browser shows this error after printing `1`:
```ERROR kyo.logs -- [IOPromise.scala:212:21] uncaught exception java.lang.UnsupportedOperationException: fiber.block is not supported in ScalaJS``` and it never prints `2`
originally I was at `0.12.0`, the same also happens on `0.13.0`

updating to `0.13.1` will see another error at linking time, complaining about ```Referring to non-existent method constructor java.util.concurrent.ThreadFactory.<init>()void```

Is `KyoApp` intended for use in scalajs? Am I missing something? please help

### PR DESCRIPTION
**Pull request by HollandDM**
resolve #784

### CODE REVIEW

**Review by hearnadam — COMMENTED** [review]
Thanks for taking this on!

File: kyo-core/js/src/main/scala/kyo/KyoAppBasePlatformSpecific.scala [hunk 1]
```diff
@@ -0,0 +1,42 @@
+package kyo
+
+abstract class KyoAppBasePlatformSpecific extends KyoApp.Base[Throwable, Async & Resource]:
```
Comment (fwbrasil) [inline kyo-core/js/src/main/scala/kyo/KyoAppBasePlatformSpecific.scala:3]: Any specific reason why the error is in a separate type parameter? Could it be a single type param `Abort[Throwable] & Async & Resource`?

File: kyo-core/js/src/main/scala/kyo/KyoAppBasePlatformSpecific.scala [hunk 2]
```diff
@@ -0,0 +1,42 @@
...
+        Resource.run(v)
+
+    final override protected def args: Array[String] = _args
+
+    private var _args: Array[String] = null
+
+    private var concatenatedAsync: Any < (Async & Abort[Throwable]) = scala.compiletime.uninitialized
+    private var initCode: () => Unit                                = scala.compiletime.uninitialized
+
+    private def keepAlive(using Frame): Unit < (Async & Abort[Throwable]) = Async.sleep(timeout).map(_ => keepAlive)
```
[the remark this answers is not in the document]
Comment (fwbrasil) [reply kyo-core/js/src/main/scala/kyo/KyoAppBasePlatformSpecific.scala:16]: It'd be good to make the keep alive configurable as a method that can be overriden like `timeout`. There are new APIs in `Clock` for scheduled execution as well: 

```scala
val keepAliveTask = Clock.repeatWithDelay(keepAliveInterval)(())
```

It returns a `Fiber`, I think we'd also need to interrupt it once the execution has finished.

File: kyo-core/js/src/main/scala/kyo/KyoAppBasePlatformSpecific.scala [hunk 3]
```diff
@@ -0,0 +1,42 @@
...
+
+    protected def handle[A: Flat](v: A < (Async & Resource & Abort[Throwable]))(using Frame): A < (Async & Abort[Throwable]) =
+        Resource.run(v)
+
+    final override protected def args: Array[String] = _args
+
+    private var _args: Array[String] = null
+
+    private var concatenatedAsync: Any < (Async & Abort[Throwable]) = scala.compiletime.uninitialized
+    private var initCode: () => Unit                                = scala.compiletime.uninitialized
```
Comment (fwbrasil) [inline kyo-core/js/src/main/scala/kyo/KyoAppBasePlatformSpecific.scala:14]: Can you use `Maybe` to avoid `null`?

File: kyo-core/js/src/main/scala/kyo/KyoAppBasePlatformSpecific.scala [hunk 4]
```diff
@@ -0,0 +1,42 @@
...
+        if null eq concatenatedAsync.asInstanceOf[Object] then
+            concatenatedAsync = handle(v)
+        else
+            concatenatedAsync = concatenatedAsync.map(_ => handle(v))
+        end if
+
+        initCode = (
+            () =>
+                if null ne concatenatedAsync.asInstanceOf[Object] then
+                    val finalAsync = Async.race(concatenatedAsync.map(_ => ()), keepAlive)
```
Comment (fwbrasil) [inline kyo-core/js/src/main/scala/kyo/KyoAppBasePlatformSpecific.scala:34]: Nice, I see now that `keepAlive` will be interrupted by the race

File: kyo-core/js/src/main/scala/kyo/KyoAppBasePlatformSpecific.scala [hunk 5]
```diff
@@ -0,0 +1,42 @@
...
+    private var _args: Array[String] = null
+
+    private var concatenatedAsync: Any < (Async & Abort[Throwable]) = scala.compiletime.uninitialized
+    private var initCode: () => Unit                                = scala.compiletime.uninitialized
+
+    private def keepAlive(using Frame): Unit < (Async & Abort[Throwable]) = Async.sleep(timeout).map(_ => keepAlive)
+
+    final def main(args: Array[String]) =
+        this._args = args
+        if initCode ne null then initCode()
```
Comment (fwbrasil) [inline kyo-core/js/src/main/scala/kyo/KyoAppBasePlatformSpecific.scala:20]: I think we could throw an exception in case the `App` has no `run` calls. I imagine some users might try to define `def run` like in other effect systems and it'd just not execute anything silently.

File: kyo-core/js/src/main/scala/kyo/KyoAppBasePlatformSpecific.scala [hunk 6]
```diff
@@ -0,0 +1,42 @@
...
+
+    override protected def run[A: Flat](v: => A < (Async & Resource & Abort[Throwable]))(using Frame): Unit =
+        import AllowUnsafe.embrace.danger
+
+        if null eq concatenatedAsync.asInstanceOf[Object] then
+            concatenatedAsync = handle(v)
+        else
+            concatenatedAsync = concatenatedAsync.map(_ => handle(v))
```
Comment (fwbrasil) [inline kyo-core/js/src/main/scala/kyo/KyoAppBasePlatformSpecific.scala:28]: I like this workaround to chain `run` calls!

File: kyo-core/jvm/src/main/scala/kyo/KyoAppBasePlatformSpecific.scala [hunk 7]
```diff
@@ -0,0 +1,28 @@
...
+
+    final def main(args: Array[String]) =
+        this._args = args
+        for proc <- initCode do proc()
+
+    override protected def run[A: Flat](v: => A < (Async & Resource & Abort[Throwable]))(using Frame): Unit =
+        import AllowUnsafe.embrace.danger
+        initCode += (() =>
+            val result = IO.Unsafe.run(Abort.run(Async.runAndBlock(timeout)(handle(v)))).eval
+            if !result.exists(().equals(_)) then println(pprint.apply(result).plainText)
```
Comment (fwbrasil) [inline kyo-core/jvm/src/main/scala/kyo/KyoAppBasePlatformSpecific.scala:25]: `!result.contains(())`

File: kyo-core/jvm/src/main/scala/kyo/KyoAppBasePlatformSpecific.scala [hunk 8]
```diff
@@ -0,0 +1,28 @@
+package kyo
+
+import scala.collection.mutable.ListBuffer
+
+abstract class KyoAppBasePlatformSpecific extends KyoApp.Base[Throwable, Async & Resource]:
+    override def timeout: Duration = Duration.Infinity
+
+    protected def handle[A: Flat](v: A < (Async & Resource & Abort[Throwable]))(using Frame): A < (Async & Abort[Throwable]) =
```
[the remark this answers is not in the document]
Comment (HollandDM) [reply kyo-core/jvm/src/main/scala/kyo/KyoAppBasePlatformSpecific.scala:8]: Yes, I’ll update this

File: kyo-core/js/src/main/scala/kyo/KyoAppBasePlatformSpecific.scala (hunk 1 above)
Comment (HollandDM) [reply kyo-core/js/src/main/scala/kyo/KyoAppBasePlatformSpecific.scala:3]: Yes, I think its because of my initial attempt in which handle initially returned Fiber[E, A] < IO, so I encode both E and A on the signature. It should just encodes A and lock E to Throwable

File: kyo-core/js/src/main/scala/kyo/KyoAppBasePlatformSpecific.scala [hunk 9]
```diff
@@ -0,0 +1,42 @@
...
+        end if
+
+        initCode = (
+            () =>
+                if null ne concatenatedAsync.asInstanceOf[Object] then
+                    val finalAsync = Async.race(concatenatedAsync.map(_ => ()), keepAlive)
+                    val _          = IO.Unsafe.run(Async.run(finalAsync)).eval
+                else
+                    (
+                )
```
[the remark this answers is not in the document]
Comment (HollandDM) [reply kyo-core/js/src/main/scala/kyo/KyoAppBasePlatformSpecific.scala:38]: In JVM we have blocking, so initCode can be sequentially run. In JS we can’t block, so if we run them like we did in JVM, they’ll be spawned as JS promise by the runtime, hence the order of execution is not guaranteed. That why in JS code I concatenate the initCode into a single one.
I didn’t do this concatenation in main method because it requires Frames implicitly, and I was not sure if I want to use Frames.internal or not

File: kyo-core/js/src/main/scala/kyo/KyoAppPlatformSpecific.scala [hunk 10]
```diff
@@ -0,0 +1,41 @@
...
+    final override protected def run[A: Flat](v: => A < (Async & Resource & Abort[Throwable]))(using Frame): Unit =
+        import AllowUnsafe.embrace.danger
+        val currentFiberIO =
+            for
+                currentFiber <- handle(v).flatMap(_.mapResult { result =>
+                    IO(Result(if !result.exists(().equals(_)) then println(pprint.apply(result).plainText)))
+                })
+                sleepFiber <- Async.run(Async.sleep(timeout))
+                raceFiber  <- Fiber.race(Seq(currentFiber.get, sleepFiber.get))
+            yield raceFiber
```
Comment (HollandDM) [inline kyo-core/js/src/main/scala/kyo/KyoAppPlatformSpecific.scala:19]: I try to get the same behavior on the JVM side, by racing this with a `Async.sleep`

File: kyo-core/jvm/src/main/scala/kyo/KyoAppPlatformSpecific.scala [hunk 11]
```diff
@@ -0,0 +1,25 @@
...
+    private val procListBuffer = new ListBuffer[() => Unit]
+
+    final override protected def run[A: Flat](v: => A < (Async & Resource & Abort[Throwable]))(using Frame): Unit =
+        import AllowUnsafe.embrace.danger
+        procListBuffer += (() =>
+            val resultEffect = handle(v).map { fiber =>
+                fiber.block(timeout).map(Abort.get(_))
+            }
+            val result = IO.Unsafe.run(Abort.run(resultEffect)).eval
+            if !result.exists(().equals(_)) then println(pprint.apply(result).plainText)
```
Comment (HollandDM) [inline kyo-core/jvm/src/main/scala/kyo/KyoAppPlatformSpecific.scala:16]: Compiler will complain about strict equality of `A | Unit` if we use `!result.contains(_)` here, i guess that why it's been like this from the start.

File: kyo-core/js/src/main/scala/kyo/KyoAppPlatformSpecific.scala [hunk 12]
```diff
@@ -0,0 +1,41 @@
...
+            maybeProc = Present(() =>
+                previousFiberIO match
+                    case Present(fiberIO) =>
+                        val combinedFiberIO =
+                            for
+                                keepAliveFiber <- Clock.repeatWithDelay(1.hours)(())
+                                fiber          <- fiberIO
+                                combineFiber   <- Fiber.race(Seq(keepAliveFiber.get, fiber.get))
+                            yield combineFiber
+                        val _ = IO.Unsafe.run(Async.run(combinedFiberIO.get)).eval
```
Comment (hearnadam) [inline kyo-core/js/src/main/scala/kyo/KyoAppPlatformSpecific.scala:35]: I don't think you need to use `Async.run` or `combinedFiberIO.get` but I could be wrong.

File: kyo-core/js/src/main/scala/kyo/KyoAppPlatformSpecific.scala [hunk 13]
```diff
@@ -0,0 +1,41 @@
...
+
+abstract class KyoAppPlatformSpecific extends KyoApp.Base[Async & Resource & Abort[Throwable]]:
+
+    private var previousFiberIO: Maybe[Fiber[Throwable, Unit] < IO] = Absent
+
+    final override protected def run[A: Flat](v: => A < (Async & Resource & Abort[Throwable]))(using Frame): Unit =
+        import AllowUnsafe.embrace.danger
+        val currentFiberIO =
+            for
+                currentFiber <- handle(v).flatMap(_.mapResult { result =>
```
[the remark this answers is not in the document]
Comment (hearnadam) [reply kyo-core/js/src/main/scala/kyo/KyoAppPlatformSpecific.scala:14]: I think that's probably a good thing. If a user cancels a run, they will want to cancel all.

[the remark this answers is not in the document]
Comment (hearnadam) [reply kyo-core/js/src/main/scala/kyo/KyoAppPlatformSpecific.scala:14]: You can probably also use `.unsafe.onComplete(printResult)` to avoid needing the `IO(Result(...`

File: kyo-core/js/src/main/scala/kyo/KyoAppPlatformSpecific.scala [hunk 14]
```diff
@@ -0,0 +1,41 @@
...
+                    IO(Result(if !result.exists(().equals(_)) then println(pprint.apply(result).plainText)))
+                })
+                sleepFiber <- Async.run(Async.sleep(timeout))
+                raceFiber  <- Fiber.race(Seq(currentFiber.get, sleepFiber.get))
```
Comment (hearnadam) [inline kyo-core/js/src/main/scala/kyo/KyoAppPlatformSpecific.scala:18]: `Async.timeout`?

**Review by hearnadam — COMMENTED** [review]
Do you mind adding a test with multiple `run`s if we don't have one already?

I think it can be as simple as building a list of runs

```
val x = ListBuffer...
object TestApp extends KyoApp:
  run { IO(x += 1) }
  run { IO(x += 2) }
TestApp.main(Array.empty)
assert(x == Seq(1, 2, 3....)
```

File: kyo-core/js/src/main/scala/kyo/KyoAppPlatformSpecific.scala (hunk 13 above)
[the remark this answers is not in the document]
Comment (HollandDM) [reply kyo-core/js/src/main/scala/kyo/KyoAppPlatformSpecific.scala:14]: `.unsafe.onComplete(printResult)` gives me `Unit < IO`, but i need `Fiber[Throwable, Unit] < IO` here

File: kyo-core/js/src/main/scala/kyo/KyoAppPlatformSpecific.scala (hunk 12 above)
Comment (HollandDM) [reply kyo-core/js/src/main/scala/kyo/KyoAppPlatformSpecific.scala:35]: most of these back and forth `fiber.get` and `Async.run` are just to convert between `Fiber[E, A]` and `A < (Async & Abort[E])` to use the method. I feel like some APIs can be update here:
- `Fiber.race` should receive `Fiber` seq, currently it's receiving `A < (Async & Abort[E])`
- There is no `timeout` or `sleep` for `Fiber`, only available now on `A < (Async & Abort[E])`

**Comment by HollandDM** [comment]
Updated the code a bit, and added a small test for KyoApp in js

File: kyo-core/js/src/main/scala/kyo/KyoAppPlatformSpecific.scala (hunk 13 above)
[the remark this answers is not in the document]
Comment (HollandDM) [reply kyo-core/js/src/main/scala/kyo/KyoAppPlatformSpecific.scala]: I changed the code to use Async, which is friendlier IMO

**Comment by HollandDM** [comment]
Updated, fix and add one more test for KyoApp on JS

**Comment by HollandDM** [comment]
Updated, squash commits

File: kyo-core/shared/src/main/scala/kyo/KyoApp.scala [hunk 15]
```diff
@@ -30,21 +25,28 @@ object KyoApp:
...
-        private val initCode = new ListBuffer[() => Unit]
+        protected var maybeProc: Maybe[() => Unit] = Absent
 
         final def main(args: Array[String]) =
             this._args = args
-            for proc <- initCode do proc()
+            maybeProc match
+                case Present(proc) => proc()
+                case Absent        => ()
+        end main
```
Comment (hearnadam) [inline kyo-core/shared/src/main/scala/kyo/KyoApp.scala:43]:
```suggestion
            for proc <- initCode do proc()
```

File: kyo-core/shared/src/test/scala/kyo/KyoAppTest.scala [hunk 16]
```diff
@@ -30,6 +34,17 @@ class KyoAppTest extends Test:
             runs <- ref.get
         yield assert(runs == 3)
     }
+    "multiple runs on JS" taggedAs jsOnly in {
```
Comment (hearnadam) [inline kyo-core/shared/src/test/scala/kyo/KyoAppTest.scala:37]: This test is necessary for JVM and JS. We can delete the other one.

```suggestion
    "ordered runs" in {
```

File: kyo-core/shared/src/main/scala/kyo/KyoApp.scala [hunk 17]
```diff
@@ -30,21 +25,28 @@ object KyoApp:
...
 
-        protected def handle[A: Flat](v: A < S)(using Frame): Unit
+        protected def handle[A: Flat](v: A < S)(using Frame): A < (Async & Abort[Throwable])
 
         final protected def args: Array[String] = _args
 
         private var _args: Array[String] = null
 
-        private val initCode = new ListBuffer[() => Unit]
+        protected var maybeProc: Maybe[() => Unit] = Absent
```
Comment (hearnadam) [inline kyo-core/shared/src/main/scala/kyo/KyoApp.scala:36]: Can this be `Iterable[() => Unit]`? Or `IterableOnce`? I think the changes in this PR break multiple runs on JVM.

File: kyo-core/jvm/src/main/scala/kyo/KyoAppPlatformSpecific.scala [hunk 18]
```diff
@@ -0,0 +1,22 @@
...
+
+    private val procListBuffer = new ListBuffer[() => Unit]
+
+    final override protected def run[A: Flat](v: => A < (Async & Resource & Abort[Throwable]))(using Frame): Unit =
+        import AllowUnsafe.embrace.danger
+        procListBuffer += (() =>
+            val result = IO.Unsafe.run(Abort.run(Async.runAndBlock(timeout)(handle(v)))).eval
+            printResult(result)
+        )
+        if maybeProc.isEmpty then
```
Comment (hearnadam) [inline kyo-core/jvm/src/main/scala/kyo/KyoAppPlatformSpecific.scala:15]: Won't this only be `true` once? I think we can make the `maybeProc` a generic Iterable:

`private var initCode: Iterable[() => Unit] = Nil`

Then we can just always update it. Both versions should be able to conform to this signature.

Scala JS:
`initCode = maybeProc.toList`
jvm
`initCode = procListBuffer.toList`

Comment (HollandDM) [reply kyo-core/jvm/src/main/scala/kyo/KyoAppPlatformSpecific.scala:15]: I think I understand what you're trying to say now, I'll try to update this.

File: kyo-core/js/src/main/scala/kyo/KyoAppPlatformSpecific.scala [hunk 19]
```diff
@@ -0,0 +1,30 @@
...
+
+    private var maybePreviousAsync: Maybe[Unit < (Async & Abort[Throwable])] = Absent
+
+    final override protected def run[A: Flat](v: => A < (Async & Resource & Abort[Throwable]))(using Frame): Unit =
+        import AllowUnsafe.embrace.danger
+        val currentAsync: Unit < (Async & Abort[Throwable]) =
+            Async.timeout(timeout)(handle(v)).map(value => printResult(Result.success(value)))
+        maybePreviousAsync = maybePreviousAsync match
+            case Absent                 => Present(currentAsync)
+            case Present(previousAsync) => Present(previousAsync.map(_ => currentAsync))
```
Comment (HollandDM) [inline kyo-core/js/src/main/scala/kyo/KyoAppPlatformSpecific.scala:16]: updated

File: kyo-core/jvm/src/main/scala/kyo/KyoAppPlatformSpecific.scala [hunk 20]
```diff
@@ -0,0 +1,15 @@
+package kyo
+
+import scala.collection.mutable.ListBuffer
+
+abstract class KyoAppPlatformSpecific extends KyoApp.Base[Async & Resource & Abort[Throwable]]:
+
+    final override protected def run[A: Flat](v: => A < (Async & Resource & Abort[Throwable]))(using Frame): Unit =
+        import AllowUnsafe.embrace.danger
+        initCode += (() =>
```
Comment (HollandDM) [inline kyo-core/jvm/src/main/scala/kyo/KyoAppPlatformSpecific.scala:9]: JVM side, code is pretty much the same

File: kyo-core/js/src/main/scala/kyo/KyoAppPlatformSpecific.scala [hunk 21]
```diff
@@ -0,0 +1,30 @@
...
+import kyo.Maybe.Present
+
+abstract class KyoAppPlatformSpecific extends KyoApp.Base[Async & Resource & Abort[Throwable]]:
+
+    private var maybePreviousAsync: Maybe[Unit < (Async & Abort[Throwable])] = Absent
+
+    final override protected def run[A: Flat](v: => A < (Async & Resource & Abort[Throwable]))(using Frame): Unit =
+        import AllowUnsafe.embrace.danger
+        val currentAsync: Unit < (Async & Abort[Throwable]) =
+            Async.timeout(timeout)(handle(v)).map(value => printResult(Result.success(value)))
```
Comment (hearnadam) [inline kyo-core/js/src/main/scala/kyo/KyoAppPlatformSpecific.scala:13]: If you put the `timeout` within the initiation of the Unit function, (when you update `initCode`) you will avoid some sleep fibers and potentially racy behavior.

I think it makes sense to timeout the whole application anyways.

File: kyo-core/js/src/main/scala/kyo/KyoAppPlatformSpecific.scala [hunk 22]
```diff
@@ -0,0 +1,30 @@
...
+        maybePreviousAsync = maybePreviousAsync match
+            case Absent                 => Present(currentAsync)
+            case Present(previousAsync) => Present(previousAsync.map(_ => currentAsync))
+        if initCode.isEmpty then
```
Comment (hearnadam) [inline kyo-core/js/src/main/scala/kyo/KyoAppPlatformSpecific.scala:17]: I was initially wondering **why** this would work, when only the first fiber would be initialized, but then I realized the first fiber would begin the execution of the next...

In my testing, I think this code also causes `repeatWithDelay` to run forever. The `run` fiber is already complete when the `timeout` expires.

Regardless, I re-wrote this a bit which I think is a simplification:

```scala
package kyo

import kyo.Maybe.Absent
import kyo.Maybe.Present

abstract class KyoAppPlatformSpecific extends KyoApp.Base[Async & Resource & Abort[Throwable]]:

    private var previous: Maybe[Unit < (Async & Abort[Throwable])] = Absent

    final override protected def run[A: Flat](v: => A < (Async & Resource & Abort[Throwable]))(using Frame): Unit =
        import AllowUnsafe.embrace.danger
        val current: Unit < (Async & Abort[Throwable]) =
            Abort.run(handle(v)).map(result => IO(printResult(result)).andThen(Abort.get(result)).unit)

        previous = previous match
            case Absent            => Present(current)
            case Present(p) => Present(p.map(_ => current))

        initCode = previous.map { async => () =>
            val raced = Clock.repeatWithDelay(1.hour)(()).map { fiber =>
                val race = Async.race(fiber.get, async)
                Async.timeout(timeout)(race)
            }
            val _ = IO.Unsafe.run(Async.run(raced)).eval
        }.toList

    end run

end KyoAppPlatformSpecific
```

In `KyoApp` I made `initCode` a variable with a List for ease of conversion with Maybe.
```scala
protected var initCode: List[() => Unit] = List.empty
```

You can check if the Clock fiber is still running by changing `()` to a `Console.println` and increase the frequency of heartbeat.

File: kyo-core/shared/src/test/scala/kyo/KyoAppTest.scala [hunk 23]
```diff
@@ -30,20 +34,47 @@ class KyoAppTest extends Test:
...
         yield assert(runs == 3)
     }
-    "effects" taggedAs jvmOnly in {
+    "orderred runs" in {
+        val x       = new ListBuffer[Int]
+        val promise = scala.concurrent.Promise[Assertion]()
+        val app = new KyoApp:
+            run { IO(x += 1) }
+            run { IO(x += 2) }
+            run { IO(x += 3) }
```
Comment (hearnadam) [inline kyo-core/shared/src/test/scala/kyo/KyoAppTest.scala:43]: Let's mix in `Async` just for posterity:

```scala
            run { Abort.delay(10.millis)(IO(x += 1)) }
            run { Async.delay(10.millis)(IO(x += 2)) }
            run { Async.delay(10.millis)(IO(x += 3)) }
```

File: kyo-core/js/src/main/scala/kyo/KyoAppPlatformSpecific.scala (hunk 21 above)
Comment (HollandDM) [reply kyo-core/js/src/main/scala/kyo/KyoAppPlatformSpecific.scala:13]: I mimiced the code in JVM (timeout for each `run`s). Will updated this

**Comment by fwbrasil** [comment]
folks, anything pending to merge this? We can follow up with improvements if needed. It'd be nice to get the issue fixed.

**Comment by HollandDM** [comment]
I'll try to finalize this in the upcoming days, I think there aer only some little code conventions/styles left to adjust

**Comment by HollandDM** [comment]
@fwbrasil @hearnadam I've updated the code, it should be good now

**Review by hearnadam — APPROVED** [review]

File: kyo-core/jvm/src/main/scala/kyo/KyoAppPlatformSpecific.scala [hunk 24]
```diff
@@ -0,0 +1,15 @@
+package kyo
+
+import scala.collection.mutable.ListBuffer
+
+abstract class KyoAppPlatformSpecific extends KyoApp.Base[Async & Resource & Abort[Throwable]]:
```
Comment (fwbrasil) [inline kyo-core/jvm/src/main/scala/kyo/KyoAppPlatformSpecific.scala:5]: The build is failing in Native. I think it's just a matter of moving this file to `kyo-core/jvm-native/src/`

Comment (HollandDM) [reply kyo-core/jvm/src/main/scala/kyo/KyoAppPlatformSpecific.scala]: updated and tested, should work now

**Review by hearnadam — APPROVED** [review]
