### PR TITLE
fixes #1271 restore should work with multishot

### LINKED ISSUE #1271: [BUG]: Var.isolate.merge doesn't work on multishot ?
### Version

main

### Scala Version

3.7.0

### Expected Behavior

on
```scala
            "with multishot" in run {
                val result: (Int, Chunk[Int]) < Any = Var.runTuple(1) {
                    Choice.run:
                        Choice.eval(1, 2, 3).map: i =>
                            Var.update[Int](_ + i)
                }

                assert(result.eval == (1 + 1 + 2 + 3, Chunk(2, 4, 7)))

                val resultIsolate: (Int, Chunk[Int]) < Any = Var.runTuple(1) {
                    Choice.run:
                        Var.isolate.merge[Int](_ + _).run:
                            Choice.eval(1, 2, 3).map: i =>
                                Var.update[Int](_ + i)
                }

                assert(resultIsolate.eval == (1 + 2 + 3 + 4, Chunk(2, 3, 4)))
            }
```

test should pass

### Actual Behavior

```
[info]   - with multishot *** FAILED *** (32 milliseconds)
[info]     (5, Chunk.Indexed(2, 3, 4)) did not equal (10, Chunk.Indexed(2, 3, 4)) (VarTest.scala:167)
[info]     Analysis:
[info]     Tuple2(_1: 5 -> 10)
```

The computation is properly isolated, but not restored.

### Steps to Reproduce

_No response_

### Current Workaround

_No response_

### PR DESCRIPTION
**Pull request by ahoy-jon**
fixes #1271

### CODE REVIEW

File: kyo-prelude/shared/src/main/scala/kyo/Var.scala [hunk 1]
```diff
@@ -237,7 +237,10 @@ object Var:
         def merge[V](using Tag[Var[V]])[S](f: (V, V) => V < S): Isolate.Stateful[Var[V], S] =
             new Base[V, S]:
                 def restore[A, S2](v: (V, A) < S2)(using Frame) =
-                    Var.use[V](prev => v.map((state, r) => f(prev, state).map(Var.setWith(_)(r))))
+                    v.map: (state, a) =>
+                        Var.get[V].map: prev =>
```
Comment (hearnadam) [inline kyo-prelude/shared/src/main/scala/kyo/Var.scala]:
```suggestion
                        Var.use[V]: prev =>
```

Comment (ahoy-jon) [reply kyo-prelude/shared/src/main/scala/kyo/Var.scala]: indeed, it's better!
