### PR TITLE
aborts: improve support for union types (fixes #244)

### LINKED ISSUE #244: Problem with tagged Aborts
Minified example:

```scala
                val effect1: Int < Aborts[String | Boolean] =
                    Aborts[String | Boolean].fail("failure")
                val handled1: Either[String, Int] < Aborts[Boolean] =
                    Aborts[String].run(effect1)
                val handled2: Either[Boolean, Either[String, Int]] < Any =
                    Aborts[Boolean].run(handled1)
                handled2.pure
```

This block of code throws the following crazy runtime exception:

```
java.lang.IllegalStateException: Unhandled effect: -520960862|
scala.Boolean
scala.AnyVal
kyo.Abortskyo.core$.Effectkyo.core	
|30
```

The reason, I believe, is that when the original `Aborts` effect is constructed, it summons a `ClassTag` for `String | Boolean`, permitting a handler to match on `Left[String | Boolean, Nothing]`, but when the effect is handled subsequently, the handler matches on `Left[String, Nothing]` and `Left[Boolean, Nothing]`.

Conversely, it will also fail if you compose two `Aborts` effects constructed with different failure types and try to handle the union:

```scala
                val effect: Int < Aborts[String | Boolean] =
                    Aborts[String].fail("failure")
                val handled: Either[String | Boolean, Int] < Any =
                    Aborts[String | Boolean].run(effect)
                handled.pure
```

This is a big problem: it means that, given an effect `A < Aborts[E1 | E2 | E3| ... | EN]`, it is impossible to know how these errors can be handled without causing a runtime error.

I can see two possible ways to solve this problem:

1. Use reflection to check whether an `Aborts` command (i.e., `Left[V, Nothing]`) has an error type that is a _subtype_ of the handler's error type. I think this is possible by comparing `LightTypeTag`s, but I'm not sure.
2. Don't check types at all: when you handle `Envs` you have to handle all of them. In this case, you'd probably want to make `Options` a separate effect.

### PR DESCRIPTION
**Pull request by fwbrasil**
Kyo currently only checks effect tags for equality, which isn't enough for effects like `Aborts`. See https://github.com/getkyo/kyo/issues/244 for more background.

This PR introduces a new method to `Handler` called `accepts`, which can be overriden with custom tag matching logic. I've added the override to `Aborts` to consider sub-typing for it and it seems to fix the issue.

I noticed another issue with the API not enabling handling of a super class and added a pending test for it. I think we'd need to add variance to `HasAborts` to fix it.

### CODE REVIEW

File: kyo-core/jvm/src/test/scala/kyoTest/coreBytecodeSizeTest.scala [hunk 1]
```diff
@@ -38,7 +38,7 @@ class coreBytecodeSizeTest extends KyoTest:
         assert(map == Map(
             "test"        -> 28,
             "resultLoop"  -> 112,
-            "handleLoop"  -> 280,
+            "handleLoop"  -> 264,
```
Comment (fwbrasil) [inline kyo-core/jvm/src/test/scala/kyoTest/coreBytecodeSizeTest.scala:41]: There are fewer bytecodes to invoke `handler.accepts` than to perform the equality check.

File: kyo-core/shared/src/main/scala/kyo/aborts.scala [hunk 2]
```diff
@@ -13,8 +13,8 @@ object Aborts:
 
     extension [V](self: Aborts[V])
 
-        def fail[T](value: T)(using ev: T => V, t: Tag[Aborts[V]]): Nothing < Aborts[V] =
-            self.suspend[Nothing](Left(ev(value)))
+        def fail[T <: V](value: T)(using t: Tag[Aborts[T]]): Nothing < Aborts[T] =
```
Comment (fwbrasil) [inline kyo-core/shared/src/main/scala/kyo/aborts.scala:16]: I've changed this method to suspend the specific type of the parameter. For example `Aborts[Throwable].fail(new Exception` will now return a `T < Aborts[Exception]`.

**Review by hearnadam — APPROVED** [review]
